server:
  port: 9090
  
spring:
  mail:
    host: smtp.gmail.com
    username: bootchatapp@gmail.com
    password: Kkavitha@123
    port: 587
    properties:
      mail:
        smtp: 
          starttls: 
            enable: true